# Generated by Django 4.1.4 on 2022-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('estado', models.CharField(choices=[('1', 'Iniciando'), ('2', 'Procesando'), ('3', 'Procesado'), ('4', 'Error')], max_length=1)),
            ],
        ),
    ]
