# Generated by Django 4.1.4 on 2022-12-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('creacion', models.DateTimeField(auto_now=True)),
                ('semana', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pais')),
                ('reportes', models.ManyToManyField(blank=True, to='informe.reportebase')),
            ],
        ),
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(choices=[('1', 'png'), ('2', 'jpg')], max_length=1)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informe.informe')),
            ],
        ),
    ]
